name: tree-whisper-app
services:
  database:
    image: postgres:latest
    container_name: tree-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_volume:/var/lib/postgresql/data

  server:
    container_name: tree-server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
        SERVER_HOST: ${SERVER_HOST}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:${SERVER_PORT}/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - tree-postgres
    networks:
      - app-network

  client:
    container_name: tree-client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      args:
        SERVER_URL: ${SERVER_URL}
        SERVER_HOST: ${SERVER_HOST}
        SERVER_PORT: ${SERVER_PORT}
        CLIENT_PORT: ${CLIENT_PORT}
    ports:
      - "${CLIENT_PORT}:80"
    networks:
      - app-network
    depends_on:
      - tree-server

networks:
  app-network:
    driver: bridge

volumes:
  db_volume:
